* Bash

  - [[https://devhints.io/bash][Bash scripting cheatsheet]]
  - [[https://tldp.org/LDP/abs/html/][Advanced Bash-Scripting Guide]]: an in-depth exploration of the art
    of shell scripting
  - [[https://github.com/dylanaraps/pure-bash-bible][pure bash bible]]: a collection of pure bash alternatives to
    external processes
  - [[https://mywiki.wooledge.org/BashFAQ][BashFAQ]]: do *not* sleep on this, it's a gold mine

** How to execute a loop conditionally (dry runs)

   #+begin_src shell
     #!/bin/bash
     doit=0

     for i in {1..3}; do
	 echo -n ${i}
     done

     echo "---"

     for i in {1..3}; do
	 ((doit))&&(echo -n ${i})
     done

     echo "---"

     for i in {1..3}; do
	 ((doit))&&echo -n ${i}
     done

     echo "---"

     ((doit))&&for i in {1..3}; do
	 echo -n ${i}
     done

     echo "---"

     ((doit))&&
	 for i in {1..3}; do
	     echo -n ${i}
	 done

     echo "---"
   #+end_src

   Also =((dontdoit))!!echo "something"=

** How to open the N most recently modified files?

   #+begin_src
emacs $(/bin/ls */* --sort=time | tail -n 5)
   #+end_src

** How to cast a string to intenger?

   Cast a string to integer in bash by adding 0. It works well if the string is
   NULL.

   #+begin_src shell
     NUM="99"
     NUM=$(($NUM+0))

     NUM=""
     NUM=$(($NUM+0))
   #+end_src

   Source:
   - [[https://stackoverflow.com/a/17093431/2860744][Bash: comparing a string as an integer - Stack Overflow]]

** How to make a conditional assignment in bash for a string?

   #+begin_src shell
     ## Assign "string-true" to VAR if VARTOCHECK is equal to "string-cond"
     [ $VARTOCHECK == "string-cond" ] && VAR="string-true" || VAR="string-false"
   #+end_src

   Source:
   - [[https://unix.stackexchange.com/a/91554/88701][bash - Conditional assignment based on environment variable]]

** How to make a conditional assignment in bash for a numeric?

   Use the following expression if the assignment is numerical.

   #+begin_src shell
     ## Assign 20 if true, or 10 if false
     variable=$(( 1 > 0 ? 20 : 10 ))
   #+end_src

   Source:
   - [[https://stackoverflow.com/a/2440950/2860744][How to build a conditional assignment in bash? - Stack Overflow]]
** How to explain shell code?

   Use [[https://explainshell.com/][explainshell]] to match command-line arguments to their help text.

** How to validate check shell code?

   Use [[https://github.com/koalaman/shellcheck][shellcheck]] for warnings and suggestions for shell scripts. It can be used
   online in [[https://www.shellcheck.net/][ShellCheck.net]].
