* Linux

** How to clean up space in /boot?

   Consider removing the fallback initramfs to make temporary space. A
   definite solution is to expand the /boot folder. Edit the
   linux.preset in /etc/mkinitcpio.d/ to disable generating a new
   fallback image. Helpful when pacman throws =Partition /boot too
   full=.

   #+begin_src shell
     ls -sh /boot/initramfs-linux-fallback.img
   #+end_src

** How to determine what shell I am currently working on?

   #+begin_src shell
     ps -p $$
   #+end_src

   Source: [[https://stackoverflow.com/a/3327022/2860744][How to determine the current shell I'm working on]]

** How to find and copy all files that match a regex?

Use =rsync --parent= to keep the folder structure.

   #+begin_src shell
     find -iname '*.rds' -exec cp {} . \;
     find -iname '*.rds' -exec rsync --parent {} . \;
   #+end_src

** How to list all files whose content match a regex?

   #+begin_src shell
     find . -exec grep optimHess {} +
   #+end_src

** How to list memory used by processes in remote cluster?

#+begin_src shell
  #!/bin/sh
  squeue --me -o "%R" |
      while read -r host; do
	  ssh -n
	  "$host" "ps -o pid,user,%mem,rss,size,%cpu,command ax | grep \"r-4\"";
      done
#+end_src

** What is the keycode of this key?

Use =xev= to look for the keycode and keysym in the KeyPress or
KeyRelease event

** How to find the window dimension and position?

   Run =xwininfo= on a console and click on the target window.

** How to convert a pdf to png?

   1920 (1080p) is often a good size

#+begin_src shell
# TODO
#+end_src

   Source: [[https://unix.stackexchange.com/questions/121293/convert-every-pdf-in-the-current-directory-to-png][Convert every pdf in the current directory to png]]
