* Linux

** How to read a systemd service log for today?

   Don't forget to add =--user= if it's a user service. Also, =-b= is
   short for =-b-0= (Ghosthree3 at libera.chat)

   #+begin_src shell
     journalctl --user -u servicename -b
   #+end_src

** How to clean up space in /boot?

   Consider removing the fallback initramfs to make temporary space. A
   definite solution is to expand the /boot folder. Edit the
   linux.preset in /etc/mkinitcpio.d/ to disable generating a new
   fallback image. Helpful when pacman throws =Partition /boot too
   full=.

   #+begin_src shell
     ls -sh /boot/initramfs-linux-fallback.img
   #+end_src

** How to determine what shell I am currently working on?

   #+begin_src shell
     ps -p $$
   #+end_src

   Source: [[https://stackoverflow.com/a/3327022/2860744][How to determine the current shell I'm working on]]

** How to find and copy all files that match a regex?

   Use =rsync --parent= to keep the folder structure.

   #+begin_src shell
     find -iname '*.rds' -exec cp {} . \;
     find -iname '*.rds' -exec rsync --parent {} . \;
   #+end_src

** How to list all files whose content match a regex?

   #+begin_src shell
     find . -exec grep optimHess {} +
   #+end_src

** How to list memory used by processes in remote cluster?

   #+begin_src shell
     #!/bin/sh
     squeue --me -o "%R" |
	 while read -r host; do
	     ssh -n
	     "$host" "ps -o pid,user,%mem,rss,size,%cpu,command ax | grep \"r-4\"";
	 done
   #+end_src

** What is the keycode of this key?

   Use =xev= to look for the keycode and keysym in the KeyPress or
   KeyRelease event

** How to find the window dimension and position?

   Run =xwininfo= on a console and click on the target window.

** How to convert a pdf to png?

   1920 (1080p) is often a good size

   #+begin_src shell
     # TODO
   #+end_src

   Source: [[https://unix.stackexchange.com/questions/121293/convert-every-pdf-in-the-current-directory-to-png][Convert every pdf in the current directory to png]]

** How to switch keyboard layout to type Greek letters?

   To switch between US and Greek (polytonic) keyboard layouts using
   Alt + Caps Locks. Add to =~/.xinitrc=, or possibly
   =~/.config/i3/config=, to make it persistent.

   #+begin_src shell
     setxkbmap 'us,gr' -variant ',polytonic' -option grp:'alt_caps_toggle'
   #+end_src

** What are the keyboard layout switching keys?

   - To list them all =man xkeyboard-config= [[https://unix.stackexchange.com/a/45499/88701][Other than Alt + Shift to
     switch keyboard layout, any other Xorg key]]
   - To list the toggle keys only
     =grep "grp:.*toggle" /usr/share/X11/xkb/rules/base.lst=
     [[https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Switching_between_keyboard_layouts][Xorg/Keyboard configuration]]

** How to type math symbols, ascii emoji easily?

   Use a Compose key. Here's my .XCompose, below there are many more

   - [[https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Configuring_compose_key][Xorg/Keyboard configuration - ArchWiki]]
   - [[https://github.com/exaexa/xcompose/blob/master/.XCompose][xcompose/.XCompose at master · exaexa/xcompose · GitHub]]
   - [[https://github.com/svinota/XCompose/blob/master/.XCompose][XCompose/.XCompose at master · svinota/XCompose · GitHub]]
   - [[https://github.com/nshepperd/xcompose/blob/master/math.conf][xcompose/math.conf at master · nshepperd/xcompose · GitHub]]
   - [[https://github.com/nshepperd/xcompose/blob/master/superscripts.conf][xcompose/superscripts.conf at master · nshepperd/xcompose · GitHub]]
   - [[https://github.com/Wafelack/dotfiles/blob/master/X/.XCompose][dotfiles/.XCompose at master · Wafelack/dotfiles · GitHub]]

** How to set a compose key (=Multi_key=)?

   - To list all compose key options
     =grep "compose:" /usr/share/X11/xkb/rules/base.lst=
   - To set a compose key
     =setxkbmap -option compose:rctrl=
   - [[https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Configuring_compose_key][Xorg/Keyboard configuration - ArchWiki]]

** How to connect OBS to Zoom or Webex?

   To redirect video from OBS to a new virtual camera input
   - Install the linux headers if you don't have them, e.g,
     =sudo pacman -S linux-headers=
   - Install =v4l2loopback-dkms=, e.g., =sudo pacman -S
     v4l2loopback-dkms=
   - Load the kernel module =sudo modprobe v4l2loopback=
   - Select =Dummy video device= as video source in the meeting app,
     e.g., in Zoom Settings > Video > Camera
   - Source: [[https://wiki.archlinux.org/title/Open_Broadcaster_Software#Virtual_camera_output][Open Broadcaster Software - ArchWiki]]

   To redirect audio from OBS to a new virtual sound input
   - Create a null output device
     #+begin_src shell
       pulsemodule=$(pactl load-module module-null-sink sink_name=obs_audio
		     sink_properties=device.description=obs_audio_sink_for_mic)
     #+end_src
   - In =pavucontrol=, Playback tab, change the output of
     =OBS-monitor= to =Null output=
   - In =pavucontrol=, Recording tab, change the input of =Zoom= to
     =Null output=
   - Source:
     - MacGyver at libera.chat,
     - [[https://wiki.archlinux.org/title/PulseAudio/Examples#Monitor_specific_output][PulseAudio/Examples - ArchWiki]]
     - [[https://unix.stackexchange.com/a/604082/88701][Redirecting Pulseaudio sink to a virtual source]]
