* PDF processing

  - [[https://github.com/tesseract-ocr/tesseract][Tesseract OCR]]: neural net (LSTM) based OCR engine
  - Use [[https://www.xpdfreader.com/pdftotext-man.html][pdftotext]] instead of copying directly from a PDF
  - Use [[https://wiki.archlinux.org/index.php/Ocrdesktop][OCRdesktop]] to grab content from a screen as text
  - [[https://filingdb.com/b/pdf-text-extraction][What's so hard about PDF text extraction?]]
  - [[https://www.emacswiki.org/emacs/DeletingWhitespace][Deleting whitespaces]]

** How to convert a PDF file to a text file?

   Use =pdftotext= to extract the content of a PDF file and write it into a text
   file.

   #+begin_src shell
     pdftotext document.pdf document.txt
   #+end_src

** How to list all the fonts used in a PDF file?

   Use =pdffonts= to list all the fonts used in a PDF

   #+begin_src shell
     pdffonts document.pdf
   #+end_src

** How to extract images from a PDF file?

   Use =pdfimages= to extract images from a PDF file

   #+begin_src shell
     pdfimages -list document.pdf
     pdfimages -png -f 1 -l 10 document.pdf
   #+end_src

** How to merge PDF files?

   Use =pdfunite= to merge =input1.pdf= and =input2.pdf= into
   =merged_document.pdf=.

   #+begin_src shell
     pdfunite input1.pdf input2.pdf merged_document.pdf
   #+end_src

   Use [[https://en.wikipedia.org/wiki/Ghostscript][Ghostscript]] to merge =input1.pdf= and =input2.pdf= into
   =merged_document.pdf=.

   #+begin_src shell
     gs -sDEVICE=pdfwrite dNOPAUSE -dBATCH -dSAFER -dQUIET  \
        -dAutoRotatePages=/None \
        -sOutputFile="merged_document.pdf" input1.pdf input2.pdf
   #+end_src

   Source: [[https://askubuntu.com/a/257170][How to merge several PDF files?]]

** How to extract some pages from a PDF file?

   Use =pdfseparate= to extract page by page as sample-1.pdf, sample-2.pdf,
   sample-3.pdf.

   #+begin_src shell
     pdfseparate sample.pdf sample-%d.pdf
   #+end_src

   Use [[https://en.wikipedia.org/wiki/Ghostscript][Ghostscript]] to extract pages 12-15 from =input.pdf= into
   =extracted_document.pdf=.

   #+begin_src shell
     gs -sDEVICE=pdfwrite dNOPAUSE -dBATCH -dSAFER -dQUIET  \
          -dFirstPage=12 \
          -dLastPage=15 \
          -sOutputFile="extracted_document.pdf" \
          input.pdf
   #+end_src

   Source: [[https://askubuntu.com/a/282105/933499][How can I extract a page range / a part of a PDF?]]

** How to compress a PDF file?

   Use [[https://en.wikipedia.org/wiki/Ghostscript][Ghostscript]] to compress =input.pdf= and write into
   =compressed_document.pdf= using a [[https://www.ghostscript.com/doc/current/VectorDevices.htm#distillerparams][distiller preset]]
   - =-dPDFSETTINGS=/screen= lower quality, smaller size (72 dpi)
   - =-dPDFSETTINGS=/ebook=  better quality, slightly larger size (150
     dpi)
   - =-dPDFSETTINGS=/prepress= prepress optimized (300 dpi)
   - =-dPDFSETTINGS=/printer=  print optimized (300 dpi)
   - =-dPDFSETTINGS=/default= wide variety of uses, larger size

   #+begin_src shell
     gs -sDEVICE=pdfwrite dNOPAUSE -dBATCH -dSAFER -dQUIET  \
        -dCompatibilityLevel=1.4 \
        -dPDFSETTINGS=/ebook \
        -sOutputFile="compressed_document.pdf" input.pdf
   #+end_src

   Source: [[https://askubuntu.com/a/256449/933499][How can I reduce the file size of a scanned PDF file?]]
** How to automatically crop margins from a PDF file?

   Use =pdfcrop= to automatically crop margins from a PDF file

   #+begin_src shell
     pdfcrop document.pdf
   #+end_src

** How to extract and delete all the metadata in a PDF file?

   Use =exiftool= for reading and manipulating PDF metadata.

   #+begin_src shell
     exiftool -all:all  file.pdf ## read all the tags
     exiftool -all:all= file.pdf ## remove all the tags
   #+end_src

   Source:
   - [[https://man.archlinux.org/man/exiftool.1p][exiftool(1p) — Arch manual pages]]
   - [[https://tldr.ostera.io/exiftool][tldr | simplified, community driven man pages]]
** How to set a password for a PDF file?

Use =qpdf=, or the older and sometimes deprecated =pdftk=. Use single quotes
when including special characters. The user password is mandatory. The user and
owner passwords cannot be the same.

#+begin_src shell
  ## 128 and 256 bit encryption available in qpdf
  qpdf --encrypt 'pass1' 'pass2' 256 -- input.pdf output.pdf
  ## 128 bit or lower encryption available in pdftk
  pdftk input.pdf output output.pdf owner_pw 'pass1' user_pw 'pass2' encrypt_128bit
#+end_src

Source:
- [[https://unix.stackexchange.com/a/187405][How to set password for pdf files? - Unix & Linux Stack Exchange]]
